### ISSUE TITLE
Clean up Blazium docs

### ISSUE THREAD

**Issue by Starkium** [blazium-engine/blazium-docs#3]
We need to do a pass over the docs to make sure links and text are referring to the right things and places. 

For example, here the GitHub link is pointing back to Godot and not to Blazium

![Image](https://github.com/user-attachments/assets/a9d34af5-908a-455a-baa7-e839d141f24c)

**Comment by Starkium** [comment]
found another one, the language buttons don't do anything, the version button doesn't do anything, all the links below try to open windows explorer into an unknown "projects" directory 

![image](https://github.com/user-attachments/assets/196781fb-bbd3-4a62-9093-4b3d0d62a3a4)

**Comment by Bioblaze** [comment]
@Starkium was all of this fixed?

**Comment by Starkium** [comment]
I'll take a look this week
